### ISSUE TITLE
今天突然报错了

### ISSUE THREAD

**Issue by yanyun0** [KotoriMinami/qinglong-sign#10]
![IMG_20220319_135641](https://user-images.githubusercontent.com/91511678/159109288-406f679b-9e30-45ab-b95c-b7dc53d7ae00.jpg)
之前好好的，今天突然用不了了，重新抓包也没用，还是那样报错，求大佬解答一下

**Comment by KotoriMinami** [comment]
> ![IMG_20220319_135641](https://user-images.githubusercontent.com/91511678/159109288-406f679b-9e30-45ab-b95c-b7dc53d7ae00.jpg) 之前好好的，今天突然用不了了，重新抓包也没用，还是那样报错，求大佬解答一下

看起来是获取json相关出问题了.. 你先看看/ql/config/sg_check.json 文件存在么.. 然后看看对应的json内容格式是不是对的..

**Comment by yanyun0** [comment]
照搬的格式没问题，文件存在的，昨天还有用😂，更新了仓库出问题的

**Comment by KotoriMinami** [comment]
> 照搬的格式没问题，文件存在的，昨天还有用😂，更新了仓库出问题的

呃.. 你看看json里面是不是配置了两个.. 保留你用的那个就行
