### ISSUE TITLE
作者这个配置复制到哪呢？

### ISSUE THREAD

**Issue by kemomi** [KotoriMinami/qinglong-sign#12]
cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json

？？？？？？

**Comment by KotoriMinami** [comment]
> cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
> 
> ？？？？？？

在容器终端执行这个命令就行了，会把这个文件复制到/ql/config/这个目录  便与你修改
