### ISSUE TITLE
你好，配置运行出现以下

### ISSUE THREAD

**Issue by 2990727802** [KotoriMinami/qinglong-sign#15]
## 开始执行... 2022-07-20 21:29:42

Traceback (most recent call last):
  File "sign_copartner.py", line 12, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

## 执行结束... 2022-07-20 21:29:42 耗时 0 秒

**Comment by KotoriMinami** [comment]
> ## 开始执行... 2022-07-20 21:29:42
> Traceback (most recent call last): File "sign_copartner.py", line 12, in from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'
> 
> ## 执行结束... 2022-07-20 21:29:42 耗时 0 秒

这个问题应该是依赖没安装

**Comment by KotoriMinami** [comment]
> sg_check

这个需要你自己执行 
```shell
cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
```
复制过去

**Comment by 2990727802** [comment]
我按照那个安装了所有的依赖，lxml，wheel，pycrypto都装不上

**Comment by 2990727802** [comment]
> > sg_check
> 
> 这个需要你自己执行
> 
> ```shell
> cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
> ```
> 
> 复制过去

这个是在ssh里面执行吗

**Comment by 2990727802** [comment]
你好，方便加一下QQ咨询一下吗

**Comment by KotoriMinami** [comment]
> 你好，方便加一下QQ咨询一下吗

你qq多少 我加你

**Comment by 2990727802** [comment]
> > 你好，方便加一下QQ咨询一下吗
> 
> 你qq多少 我加你

2990727802
