### ISSUE TITLE
可以加个运行通知吗

### ISSUE THREAD

**Issue by tesly03** [KotoriMinami/qinglong-sign#17]
没有通知不知道每次成功没成功，可以添加server酱那些通知吗

**Comment by KotoriMinami** [comment]
> 没有通知不知道每次成功没成功，可以添加server酱那些通知吗

已经接入了青龙的推送，你直接配置好青龙的推送就行了

**Comment by tesly03** [comment]
> > 没有通知不知道每次没有成功，可以添加服务器酱那些通知吗
> 
> 已经接入了青龙的好广播，你直接配置青龙的就行了

看到了，谢谢
