### ISSUE TITLE
ck过期后重新抓包就是这个错误了！！！！！！！！！！！！

### ISSUE THREAD

**Issue by yz9999** [KotoriMinami/qinglong-sign#18]
Traceback (most recent call last):
  File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 176, in <module>
    all_data = json.loads(f.read())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \uXXXX escape: line 4 column 1403 (char 1433)

**Comment by KotoriMinami** [comment]
> Traceback (most recent call last): File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 176, in all_data = json.loads(f.read()) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Invalid \uXXXX escape: line 4 column 1403 (char 1433)

大概率是json格式不太对..

**Comment by yz9999** [comment]
> > Traceback（最近一次调用最后）：文件“/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py”，第 176 行，在 all_data = json.loads(f.read()) 文件“/usr/lib/python3.9 /json/ **init** .py”，第 346 行，加载返回 _default_decoder.decode(s) 文件“/usr/lib/python3.9/json/decoder.py”，第 337 行，解码 obj，end = self.raw_decode (s, idx=_w(s, 0).end()) 文件“/usr/lib/python3.9/json/decoder.py”，第 353 行，在 raw_decode obj 中，end = self.scan_once(s, idx ) json.decoder.JSONDecodeError: Invalid \uXXXX escape: line 4 column 1403 (char 1433)
> 
> 大是json格式对。

没有_ns

**Comment by yz9999** [comment]
> > Traceback（最近一次调用最后）：文件“/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py”，第176行，在 all_data = json.loads(f.read()) 文件“/usr/lib/python3. 9 /json/ **init** .py”，第346行，返回_default_decoder.decode(s)文件“/usr/lib/python3.9/json/decoder.py”，第337行，解码.obj，end = self raw_decode(s, idx=_w(s, 0).end()) 文件“/usr/lib/python3.9/json/decoder.py”，第353行，在raw_decode obj中，end = self.scan_once( s, idx ) json.decoder.JSONDecodeError: Invalid \uXXXX 转义: 第 4 行第 1403 列 (char 1433)
> 
> 大是json格式对。

UM_distinctid这个参数也没有

**Comment by KotoriMinami** [comment]
> decoder

少参数只会影响登录态的验证，不会造成json的解析失败，而且报错也很明显了

**Comment by yz9999** [comment]
可以了。ck里面有的东西不需要，加进去反而不行！！！

Kotori Minami ***@***.***> 于2022年8月1日周一 11:49写道：
