### ISSUE TITLE
您好，拉库后无法拷贝文件，报错如下，依赖安装如下，请问该如何解决呢

### ISSUE THREAD

**Issue by cold-sword** [KotoriMinami/qinglong-sign#19]
cp: cannot stat '/ql/repo/KotoriMinami_qinglong-sign/sg_config.json': No such file or directory
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/100510723/181909048-853c9c2e-01bf-4d0f-b6d5-c2062312f8cb.png">

**Comment by KotoriMinami** [comment]
> cp: cannot stat '/ql/repo/KotoriMinami_qinglong-sign/sg_config.json': No such file or directory <img alt="image" width="1108" src="https://user-images.githubusercontent.com/100510723/181909048-853c9c2e-01bf-4d0f-b6d5-c2062312f8cb.png">

跟依赖应该没有关系，可以进容器目录看看是不是库拉的不太对

**Comment by Cold-Sword** [comment]
库已删除后重拉，还是不能拷贝，作者是否方便加QQ请教一下呢810171397

**Comment by KotoriMinami** [comment]
> 810171397

加你了。

**Comment by KotoriMinami** [comment]
> 810171397

加你了。
