### ISSUE TITLE
pycrypto安不上啊

### ISSUE THREAD

**Issue by javaht** [KotoriMinami/qinglong-sign#2]
用的腾讯云  死活安不上  好兄弟是怎么安的  网上的教程看遍了...

**Comment by Tamshen** [comment]
这个需要一步步依次安装，不能使用网页端新建依赖的自动拆分。
记录下流程：依赖管理
Linux
```
python3-dev
gcc
musl-dev
libxslt-dev
```
Python3
```
wheel
lxml
requests-html
```


> 更多详细：https://github.com/whyour/qinglong/issues/990#issuecomment-993427433

**Comment by KotoriMinami** [comment]
试试楼上那哥们说的 ， 还有看看你提示错误是啥..
我记得好像是还需要这么个依赖 
```shell 
apk add --no-cache python3-dev
```

**Comment by Tamshen** [comment]
新方法：
