### ISSUE TITLE
运行日志，这样是哪里出了问题

### ISSUE THREAD

**Issue by yaoli159** [KotoriMinami/qinglong-sign#20]
Traceback (most recent call last):
  File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 180, in <module>
    res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n'
  File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 153, in main
    music_data, user_name = self.valid(session)
  File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 127, in valid
    data = content.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KotoriMinami** [comment]
> Traceback (most recent call last): File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 180, in res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n' File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 153, in main music_data, user_name = self.valid(session) File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 127, in valid data = content.json() File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

大概率是json的格式不对，参考 #18

**Comment by yaoli159** [comment]
> > Traceback (most recent call last): File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 180, in res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n' File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 153, in main music_data, user_name = self.valid(session) File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 127, in valid data = content.json() File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 大概率是json的格式不对，参考 #18

现在是这样，ck也重新抓了

账号1：
帐号信息: 系统错误
cookie信息: Cookie 可能过期

网易音乐合伙人

账号1：
帐号信息: 系统错误
cookie信息: Cookie 可能过期

**Comment by KotoriMinami** [comment]
> > > Traceback (most recent call last): File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 180, in res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n' File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 153, in main music_data, user_name = self.valid(session) File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 127, in valid data = content.json() File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > 
> > 
> > 大概率是json的格式不对，参考 #18
> 
> 现在是这样，ck也重新抓了
> 
> 账号1： 帐号信息: 系统错误 cookie信息: Cookie 可能过期
> 
> 网易音乐合伙人
> 
> 账号1： 帐号信息: 系统错误 cookie信息: Cookie 可能过期

这个应该就是抓的cookie有问题了，然后不好意思， 刚刚看了下，上面那个报错可能是因为网易云的接口改了请求头的验证规则，我重新提交了一下代码，你更新一下然后重新抓cookie再试试

**Comment by yaoli159** [comment]
> > > > Traceback (most recent call last): File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 180, in res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n' File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 153, in main music_data, user_name = self.valid(session) File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 127, in valid data = content.json() File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > 
> > > 
> > > 大概率是json的格式不对，参考 #18
> > 
> > 
> > 现在是这样，ck也重新抓了
> > 账号1： 帐号信息: 系统错误 cookie信息: Cookie 可能过期
> > 网易音乐合伙人
> > 账号1： 帐号信息: 系统错误 cookie信息: Cookie 可能过期
> 
> 这个应该就是抓的cookie有问题了，然后不好意思， 刚刚看了下，上面那个报错可能是因为网易云的接口改了请求头的验证规则，我重新提交了一下代码，你更新一下然后重新抓cookie再试试

谢谢大佬，解决了👍
