### ISSUE TITLE
您好，拉库后拷贝配置文件，报错如下，请问该如何解决呢 

### ISSUE THREAD

**Issue by muxila** [KotoriMinami/qinglong-sign#21]
root@qinglong:/ql $ cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
cp: cannot stat '/ql/repo/KotoriMinami_qinglong-sign/sg_config.json': No such file or directory

**Comment by muxila** [comment]
已进容器目录查看库拉的正确

**Comment by KotoriMinami** [comment]
> 已进容器目录查看库拉的正确

新版本的青龙修改了库的目录，你试试
```shell
cp /ql/data/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/data/config/sg_check.json
```
回头我改一下readme
