### ISSUE TITLE
cookie过期问题

### ISSUE THREAD

**Issue by YiCarlos** [KotoriMinami/qinglong-sign#23]
今天产生的问题，更新cookie后依旧报错

账号1：
帐号信息: 系统错误
cookie信息: Cookie 可能过期

网易音乐合伙人

账号1：
帐号信息: 系统错误
cookie信息: Cookie 可能过期

**Comment by KotoriMinami** [comment]
> 今天产生的问题，更新cookie后依旧报错
> 
> 账号1： 帐号信息: 系统错误 cookie信息: Cookie 可能过期
> 
> 网易音乐合伙人
> 
> 账号1： 帐号信息: 系统错误 cookie信息: Cookie 可能过期

感觉应该还是获取的cookie不对..  你进
https://music.163.com/
然后按f12，在控制台里面输入
```javascript 
document.cookie
```
然后把显示出来的cookie放进去试试
