### ISSUE TITLE
作者大大，请问运行这样报错应该怎么解决呢

### ISSUE THREAD

**Issue by purechow** [KotoriMinami/qinglong-sign#27]
Traceback (most recent call last):
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py", line 87, in <module>
    with open("/ql/config/sg_check.json", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'

**Comment by KotoriMinami** [comment]
> Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py", line 87, in with open("/ql/config/sg_check.json", "r", encoding="utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'

青龙v2.12.0以后调整数据目录，log、db、scripts、config等目录迁移到 /ql/data 目录，请使用下面命令的时候注意一下自己的青龙面板版本，看是否需要在路径上加/data

**Comment by purechow** [comment]
> > Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py", line 87, in with open("/ql/config/sg_check.json", "r", encoding="utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'
> 
> 
> 
> 青龙v2.12.0以后调整数据目录，log、db、scripts、config等目录迁移到 /ql/data 目录，请使用下面命令的时候注意一下自己的青龙面板版本，看是否需要在路径上加/data

**Comment by purechow** [comment]
> > Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py", line 87, in with open("/ql/config/sg_check.json", "r", encoding="utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'
> 
> 
> 
> 青龙v2.12.0以后调整数据目录，log、db、scripts、config等目录迁移到 /ql/data 目录，请使用下面命令的时候注意一下自己的青龙面板版本，看是否需要在路径上加/data

是已经看过所有议题后才提问的，路径也是有/data的版本，所以并不是我的ck问题吗

**Comment by KotoriMinami** [comment]
> > > Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py", line 87, in with open("/ql/config/sg_check.json", "r", encoding="utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'
> > 
> > 
> > 青龙v2.12.0以后调整数据目录，log、db、scripts、config等目录迁移到 /ql/data 目录，请使用下面命令的时候注意一下自己的青龙面板版本，看是否需要在路径上加/data
> 
> 是已经看过所有议题后才提问的，路径也是有/data的版本，所以并不是我的ck问题吗

看你的报错是在```/ql/config/sg_check.json```这个目录下没找到文件，大概率是你执行这一步的时候，路径没有加data
```shell
cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
```

**Comment by purechow** [comment]
> > > > Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py", line 87, in with open("/ql/config/sg_check.json", "r", encoding="utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'
> 
> > > 
> 
> > > 
> 
> > > 青龙v2.12.0以后调整数据目录，log、db、scripts、config等目录迁移到 /ql/data 目录，请使用下面命令的时候注意一下自己的青龙面板版本，看是否需要在路径上加/data
> 
> > 
> 
> > 是已经看过所有议题后才提问的，路径也是有/data的版本，所以并不是我的ck问题吗
> 
> 
> 
> 看你的报错是在```/ql/config/sg_check.json```这个目录下没找到文件，大概率是你执行这一步的时候，路径没有加data
> 
> ```shell
> 
> cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
> 
> ```
大佬，请问可以加qq咨询一下吗，已经重复操作好多遍了还是这个样子

**Comment by KotoriMinami** [comment]
> > > > > 追溯（最近调用最后）：文件“/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py”，第 87 行，在 open(“/ql/config/sg_check.json”, “r”, encoding= "utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 青龙v2.12.0以后以后目录目录，log，db scripts，config config等/ql/data目录，请
> > 
> > 
> > > 
> > 
> > 
> > > 是已经看过所有题目后才提出问题的，路况也是有/data的版本，所以并不是我的ck题目吗
> > 
> > 
> > 看你的报错是在`/ql/config/sg_check.json`这个目录下没有找到文件，大致率是你执行这一步的时候，路途没有添加数据
> > ```shell
> > cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
> > ```
> 
> 大佬，请问可以加qq咨询一下吗，已经重新操作好多遍了还是这个样子

你qq多少  我加你

**Comment by purechow** [comment]
> > > > > > 追溯（最近调用最后）：文件“/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py”，第 87 行，在 open(“/ql/config/sg_check.json”, “r”, encoding= "utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 青龙v2.12.0以后以后目录目录，log，db scripts，config config等/ql/data目录，请
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 是已经看过所有题目后才提出问题的，路况也是有/data的版本，所以并不是我的ck题目吗
> 
> > > 
> 
> > > 
> 
> > > 看你的报错是在`/ql/config/sg_check.json`这个目录下没有找到文件，大致率是你执行这一步的时候，路途没有添加数据
> 
> > > ```shell
> 
> > > cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
> 
> > > ```
> 
> > 
> 
> > 大佬，请问可以加qq咨询一下吗，已经重新操作好多遍了还是这个样子
> 
> 
> 
> 你qq多少  我加你

1491006172

**Comment by KotoriMinami** [comment]
> > > > > > > 追溯（最近调用最后）：文件“/ql/data/scripts/KotoriMinami_qinglong-sign/sign_smzdm.py”，第 87 行，在 open(“/ql/config/sg_check.json”, “r”, encoding= "utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/sg_check.json'
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 青龙v2.12.0以后以后目录目录，log，db scripts，config config等/ql/data目录，请
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 是已经看过所有题目后才提出问题的，路况也是有/data的版本，所以并不是我的ck题目吗
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 看你的报错是在`/ql/config/sg_check.json`这个目录下没有找到文件，大致率是你执行这一步的时候，路途没有添加数据
> > 
> > 
> > > >
> > 
> > 
> > > > cp /ql/repo/KotoriMinami_qinglong-sign/sg_config.json /ql/config/sg_check.json
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > 大佬，请问可以加qq咨询一下吗，已经重新操作好多遍了还是这个样子
> > 
> > 
> > 你qq多少  我加你
> 
> 1491006172

加了，纷纷扰扰

**Comment by tvcbuv** [comment]
建个群吧

**Comment by KotoriMinami** [comment]
#28
