### ISSUE TITLE
请大佬指教下

### ISSUE THREAD

**Issue by gymg** [KotoriMinami/qinglong-sign#28]
Traceback (most recent call last):
  File "sign_copartner.py", line 182, in <module>
    res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n'
  File "sign_copartner.py", line 152, in main
    music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")}
  File "sign_copartner.py", line 152, in <dictcomp>
    music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")}
IndexError: list index out of range

**Comment by KotoriMinami** [comment]
> Traceback (most recent call last): File "sign_copartner.py", line 182, in res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n' File "sign_copartner.py", line 152, in main music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")} File "sign_copartner.py", line 152, in music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")} IndexError: list index out of range
> 
> 方便可以加qq304247122

加了，纷纷扰扰

**Comment by KotoriMinami** [comment]
2点注意:
1. 确认sg_check.json文件json格式正确性
2. 确认是否为网易音乐合伙人
