### ISSUE TITLE
运行日志报错如下

### ISSUE THREAD

**Issue by tvcbuv** [KotoriMinami/qinglong-sign#29]
Traceback (most recent call last):
  File "sign_copartner.py", line 178, in <module>
    all_data = json.loads(f.read())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 637 (char 667)

使用最新的库，ck缺少‘_ns’‘UM_distinctid’和‘ntes_kaola_ad’值，ck来源music.163.com

**Comment by tvcbuv** [comment]
请教大佬及各位使用者，该如何解决，谢谢

**Comment by KotoriMinami** [comment]
> 请教大佬及各位使用者，该如何解决，谢谢

看起来是json文件格式有问题...你把内容复制到```bejson.com```里面格式化一下看看是否正确

**Comment by tvcbuv** [comment]
> > 请教大佬及各位使用者，该如何解决，谢谢
> 
> 看起来是json文件格式有问题...你把内容复制到`bejson.com`里面格式化一下看看是否正确

感谢大佬的指点，通过该网站进行转义后，脚本可以成功运行并使用了，非常感谢

**Comment by tvcbuv** [comment]
由于cookie过期，重新抓取cookie后，运行脚本不能正常进行（json校验通过）
青龙日志卡在：## 开始执行...
抓取ck时发现，‘MUSIC_U=’的长度发生了变化
猜测大概率是因为‘MUSIC_U’这个参数的问题
还请大佬指教

2023.1.28 19:40

**Comment by KotoriMinami** [comment]
> 由于cookie过期，重新抓取cookie后，运行脚本不能正常进行（json校验通过） 青龙日志卡在：## 开始执行... 抓取ck时发现，‘MUSIC_U=’的长度发生了变化 猜测大概率是因为‘MUSIC_U’这个参数的问题 还请大佬指教
> 
> 2023.1.28 19:40

感觉像是有报错.. 你在青龙面板里调试运行看看

**Comment by tvcbuv** [comment]
> 

今天运行发现和以往一样，可以正常评分了，看看之后如何
再次感谢大佬的脚本及指点
