### ISSUE TITLE
邮件通知一直让我重试

### ISSUE THREAD

**Issue by 1828543819** [KotoriMinami/qinglong-sign#36]
![image](https://github.com/KotoriMinami/qinglong-sign/assets/140577121/78d9848c-f3ed-47c1-a246-a01da4339e95)
也不知道是哪里填错了

**Comment by KotoriMinami** [comment]
> ![image](https://user-images.githubusercontent.com/140577121/276523939-78d9848c-f3ed-47c1-a246-a01da4339e95.png) 也不知道是哪里填错了

 通知是青龙面板提供的， 可能得去那边问问..
