### ISSUE TITLE
json格式没错，但是会报错

### ISSUE THREAD

**Issue by Testplayers** [KotoriMinami/qinglong-sign#39]
## 开始执行... 2024-03-06 16:30:32

Traceback (most recent call last):
  File "/ql/data/scripts/copartner.py", line 176, in <module>
    all_data = json.loads(f.read())
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 199 (char 229)

## 执行结束... 2024-03-06 16:30:32  耗时 1 秒

**Comment by Testplayers** [comment]
## 开始执行... 2024-03-06 16:33:50

Traceback (most recent call last):
  File "/ql/data/scripts/copartner.py", line 178, in <module>
    res = Copartner(_check_item).main()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/copartner.py", line 153, in main
    music_data, user_name = self.valid(session)
                            ^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/copartner.py", line 127, in valid
    data = content.json()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## 执行结束... 2024-03-06 16:33:51  耗时 1 秒

**Comment by KotoriMinami** [comment]
> ## 开始执行... 2024-03-06 16:33:50
> Traceback (most recent call last): File "/ql/data/scripts/copartner.py", line 178, in res = Copartner(_check_item).main() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ql/data/scripts/copartner.py", line 153, in main music_data, user_name = self.valid(session) ^^^^^^^^^^^^^^^^^^^ File "/ql/data/scripts/copartner.py", line 127, in valid data = content.json() ^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 900, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/**init**.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒

你把你的json数据放到[https://www.bejson.com/](https://www.bejson.com/)里面校验一下看看是否正常..

**Comment by Testplayers** [comment]
> > ## 开始执行... 2024-03-06 16:33:50
> > Traceback (most recent call last): File "/ql/data/scripts/copartner.py", line 178, in res = Copartner(_check_item).main() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ql/data/scripts/copartner.py", line 153, in main music_data, user_name = self.valid(session) ^^^^^^^^^^^^^^^^^^^ File "/ql/data/scripts/copartner.py", line 127, in valid data = content.json() ^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 900, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/**init**.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒
> 
> 你把你的json数据放到https://www.bejson.com/里面校验一下看看是否正常..

**Comment by Testplayers** [comment]
> > ## 开始执行... 2024-03-06 16:33:50
> > 回溯（最近的调用最后）：文件"/ql/data/scripts/copartner.py"，第178行，在res=Copartner(_check_item).main()^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第153行，在主music_data中，user_name=self.efficiency(session)^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第127行，在有效数据=content.json()^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/site-packages/requests/models.py"，第900行，json返回Complexjson.loads(self.text,**kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/**初始化**.py"，第346行，在加载中返回_default_decoder.decode(s)^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/decoder.py"，第337行，在decode obj中，end=self.raw_decode(s,idx=_w(s,0).end())^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^py"，第355行，在Raw_decode中引发JSONDecodeError（"期望值",s,err.value）from None json.decoder.JSONDecodeError：需要值：第1行第1列（字符0）
> > ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒
> 
> 你把你的json数据放到https://www.bejson.com/里面校验一下看看是否正常..

检验是正确的

**Comment by KotoriMinami** [comment]
> > > ## 开始执行... 2024-03-06 16:33:50
> > > 回溯（最近的调用最后）：文件"/ql/data/scripts/copartner.py"，第178行，在res=Copartner(_check_item).main()^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第153行，在主music_data中，user_name=self.efficiency(session)^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第127行，在有效数据=content.json()^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/site-packages/requests/models.py"，第900行，json返回Complexjson.loads(self.text,**kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/**初始化**.py"，第346行，在加载中返回_default_decoder.decode(s)^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/decoder.py"，第337行，在decode obj中，end=self.raw_decode(s,idx=_w(s,0).end())^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^py"，第355行，在Raw_decode中引发JSONDecodeError（"期望值",s,err.value）from None json.decoder.JSONDecodeError：需要值：第1行第1列（字符0）
> > > ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒
> > 
> > 
> > 你把你的json数据放到[https://www.bejson.com/里面校验一下看看是否正常](https://www.bejson.com/%E9%87%8C%E9%9D%A2%E6%A0%A1%E9%AA%8C%E4%B8%80%E4%B8%8B%E7%9C%8B%E7%9C%8B%E6%98%AF%E5%90%A6%E6%AD%A3%E5%B8%B8)..
> 
> 检验是正确的

你的青龙版本和config文件的路径都是啥

**Comment by Testplayers** [comment]
> > > > ## 开始执行... 2024-03-06 16:33:50
> > > > 回溯（最近的调用最后）：文件"/ql/data/scripts/copartner.py"，第178行，在res=Copartner(_check_item).main()^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第153行，在主music_data中，user_name=self.efficiency(session)^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第127行，在有效数据=content.json()^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/site-packages/requests/models.py"，第900行，json返回Complexjson.loads(self.text,**kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/**初始化**.py"，第346行，在加载中返回_default_decoder.decode(s)^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/decoder.py"，第337行，在decode obj中，end=self.raw_decode(s,idx=_w(s,0).end())^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^py"，第355行，在Raw_decode中引发JSONDecodeError（"期望值",s,err.value）from None json.decoder.JSONDecodeError：需要值：第1行第1列（字符0）
> > > > ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒
> > > 
> > > 
> > > 你把你的json数据放到[https://www.bejson.com/里面校验一下看看是否正常](https://www.bejson.com/%E9%87%8C%E9%9D%A2%E6%A0%A1%E9%AA%8C%E4%B8%80%E4%B8%8B%E7%9C%8B%E7%9C%8B%E6%98%AF%E5%90%A6%E6%AD%A3%E5%B8%B8)..
> > 
> > 
> > 检验是正确的
> 
> 你的青龙版本和config文件的路径都是啥

v2.17.2     /root/ql/data/config

**Comment by KotoriMinami** [comment]
> > > > > ## 开始执行... 2024-03-06 16:33:50
> > > > > 回溯（最近的调用最后）：文件"/ql/data/scripts/copartner.py"，第178行，在res=Copartner(_check_item).main()^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第153行，在主music_data中，user_name=self.efficiency(session)^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第127行，在有效数据=content.json()^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/site-packages/requests/models.py"，第900行，json返回Complexjson.loads(self.text,**kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/**初始化**.py"，第346行，在加载中返回_default_decoder.decode(s)^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/decoder.py"，第337行，在decode obj中，end=self.raw_decode(s,idx=_w(s,0).end())^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^py"，第355行，在Raw_decode中引发JSONDecodeError（"期望值",s,err.value）from None json.decoder.JSONDecodeError：需要值：第1行第1列（字符0）
> > > > > ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒
> > > > 
> > > > 
> > > > 你把你的json数据放到[https://www.bejson.com/里面校验一下看看是否正常](https://www.bejson.com/%E9%87%8C%E9%9D%A2%E6%A0%A1%E9%AA%8C%E4%B8%80%E4%B8%8B%E7%9C%8B%E7%9C%8B%E6%98%AF%E5%90%A6%E6%AD%A3%E5%B8%B8)..
> > > 
> > > 
> > > 检验是正确的
> > 
> > 
> > 你的青龙版本和config文件的路径都是啥
> 
> v2.17.2 /root/ql/data/config

方便把你的json文件内容发出来看看吗，cookie记得删了

**Comment by Testplayers** [comment]
> > > > > > ## 开始执行... 2024-03-06 16:33:50
> > > > > > 回溯（最近的调用最后）：文件"/ql/data/scripts/copartner.py"，第178行，在res=Copartner(_check_item).main()^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第153行，在主music_data中，user_name=self.efficiency(session)^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第127行，在有效数据=content.json()^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/site-packages/requests/models.py"，第900行，json返回Complexjson.loads(self.text,**kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/**初始化**.py"，第346行，在加载中返回_default_decoder.decode(s)^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/decoder.py"，第337行，在decode obj中，end=self.raw_decode(s,idx=_w(s,0).end())^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^py"，第355行，在Raw_decode中引发JSONDecodeError（"期望值",s,err.value）from None json.decoder.JSONDecodeError：需要值：第1行第1列（字符0）
> > > > > > ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒
> > > > > 
> > > > > 
> > > > > 你把你的json数据放到[https://www.bejson.com/里面校验一下看看是否正常](https://www.bejson.com/%E9%87%8C%E9%9D%A2%E6%A0%A1%E9%AA%8C%E4%B8%80%E4%B8%8B%E7%9C%8B%E7%9C%8B%E6%98%AF%E5%90%A6%E6%AD%A3%E5%B8%B8)..
> > > > 
> > > > 
> > > > 检验是正确的
> > > 
> > > 
> > > 你的青龙版本和config文件的路径都是啥
> > 
> > 
> > v2.17.2 /root/ql/data/config
> 
> 方便把你的json文件内容发出来看看吗，cookie记得删了

{
"MUSIC_COPARTNER": [
    {
      "cookie": ""
    }
  ]
}

**Comment by KotoriMinami** [comment]
> > > > > > > ## 开始执行... 2024-03-06 16:33:50
> > > > > > > 回溯（最近的调用最后）：文件"/ql/data/scripts/copartner.py"，第178行，在res=Copartner(_check_item).main()^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第153行，在主music_data中，user_name=self.efficiency(session)^^^^^^^^^^^^^^^^^^^^^^文件"/ql/data/scripts/copartner.py"，第127行，在有效数据=content.json()^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/site-packages/requests/models.py"，第900行，json返回Complexjson.loads(self.text,**kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/**初始化**.py"，第346行，在加载中返回_default_decoder.decode(s)^^^^^^^^^^^^^^^^文件"/usr/local/lib/python3.11/json/decoder.py"，第337行，在decode obj中，end=self.raw_decode(s,idx=_w(s,0).end())^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^py"，第355行，在Raw_decode中引发JSONDecodeError（"期望值",s,err.value）from None json.decoder.JSONDecodeError：需要值：第1行第1列（字符0）
> > > > > > > ## 执行结束... 2024-03-06 16:33:51 耗时 1 秒
> > > > > > 
> > > > > > 
> > > > > > 你把你的json数据放到[https://www.bejson.com/里面校验一下看看是否正常](https://www.bejson.com/%E9%87%8C%E9%9D%A2%E6%A0%A1%E9%AA%8C%E4%B8%80%E4%B8%8B%E7%9C%8B%E7%9C%8B%E6%98%AF%E5%90%A6%E6%AD%A3%E5%B8%B8)..
> > > > > 
> > > > > 
> > > > > 检验是正确的
> > > > 
> > > > 
> > > > 你的青龙版本和config文件的路径都是啥
> > > 
> > > 
> > > v2.17.2 /root/ql/data/config
> > 
> > 
> > 方便把你的json文件内容发出来看看吗，cookie记得删了
> 
> { "MUSIC_COPARTNER": [ { "cookie": "" } ] }

这个界面截图我看看..

**Comment by KotoriMinami** [comment]
![image](https://github.com/KotoriMinami/qinglong-sign/assets/15208772/fe8a917b-9056-48a9-b1ef-5bfc5fed7b4f)

**Comment by Testplayers** [comment]
> ![image](https://private-user-images.githubusercontent.com/15208772/311920730-fe8a917b-9056-48a9-b1ef-5bfc5fed7b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTc1NzAsIm5iZiI6MTcxMDIxNzI3MCwicGF0aCI6Ii8xNTIwODc3Mi8zMTE5MjA3MzAtZmU4YTkxN2ItOTA1Ni00OGE5LWIxZWYtNWJmYzVmZWQ3YjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0MjExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjIyNWUwNzY1Zjc5N2IzNWI3NjM4M2EzZGIyZTZkZTc5ZDdkMGM3YWVlOWNmNzUwOTM2OWRkZjllMmNhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JpOR7UY0TRsngL6HCVT2oVp-IvTxcsuN2hAu-dbQrrY)

![1](https://github.com/KotoriMinami/qinglong-sign/assets/63090141/060bef2b-c945-4dcd-b316-cc7081d744e4)

**Comment by KotoriMinami** [comment]
哦，我一直在看第一张图..  报错的应该是后边..

**Comment by Testplayers** [comment]
> 哦，我一直在看第一张图.. 报错的应该是后边.. 跟配置文件没关系.. 应该是你不是音乐合伙人 所以获取数据的时候错了..

捏？我是合伙人
![Screenshot_20240312_213546](https://github.com/KotoriMinami/qinglong-sign/assets/63090141/be6bf5b2-511d-4b74-ac21-dad953dfca1e)
![Screenshot_20240312_213639](https://github.com/KotoriMinami/qinglong-sign/assets/63090141/d1619f71-c80d-4654-a824-268e62d7f2bf)

**Comment by KotoriMinami** [comment]
![image](https://github.com/KotoriMinami/qinglong-sign/assets/15208772/5747ea1f-4574-4bb2-8a8e-b587657aa0de)

脚本里面这个路径加个data试试， `/ql/data/config/sg_check.json`

**Comment by Testplayers** [comment]
可以了，谢谢
