### ISSUE TITLE
ck抓包问题

### ISSUE THREAD

**Issue by yanyun0** [KotoriMinami/qinglong-sign#4]
大佬，ck我抓不到_ns以及UM_distinctid，但是我去了这2个也能正常秒评测5首歌曲。去了没啥问题吧这两个

**Comment by KotoriMinami** [comment]
> 大佬，ck我抓不到_ns以及UM_distinctid，但是我去了这2个也能正常秒评测5首歌曲。去了没啥问题吧这两个

没问题的，只要能正常评分就行
