### ISSUE TITLE
大佬评分机制好像更新了，可以评12歌好像，可以更新一下嘛

### ISSUE THREAD

**Issue by huakair** [KotoriMinami/qinglong-sign#40]
大佬评分机制好像更新了，可以评12歌好像，可以更新一下嘛

**Comment by rainsum2022** [comment]
评分机制更新了，还有作弊机制了，感觉后续不能一直评3星了，不然感觉要无了

**Comment by tvcbuv** [comment]
根据规则不能一直评3分了，任务也需要随机运行，要想保住身份，每日的15分必须拿

**Comment by KotoriMinami** [comment]
已经开发好了,  新增逻辑：
1. 除本身的5首评论（8分），会额外再评论7首（7分），达到每日15分
2. 评分改为随机2-4（可能会影响每周结算质量，但保级是没问题的）
3. 根据评分随机选择1-3个标签
4. 每首歌随机等待15-20s 

我自己测试两天，没啥问题再上传
