### ISSUE TITLE
请问一下大佬

### ISSUE THREAD

**Issue by guan1112344** [KotoriMinami/qinglong-sign#42]
这个脚本只能评定每天基础分吗，如果可以再额外评定就更好了，因为我记得就算是随机，合伙人也算质量分

**Comment by KotoriMinami** [comment]
> 这个脚本只能评定每天基础分吗，如果可以再额外评定就更好了，因为我记得就算是随机，合伙人也算质量分

现在除了每日基础评定5首，还会额外评定7首，每天有15分
