### ISSUE TITLE
pycrypto依赖安装不上

### ISSUE THREAD

**Issue by 659797578** [KotoriMinami/qinglong-sign#7]
pycrypto依赖安装不上。。。

**Comment by KotoriMinami** [comment]
> pycrypto依赖安装不上。。。

参考#2

**Comment by 659797578** [comment]
## 开始执行... 2022-03-04 11:57:08

Traceback (most recent call last):
  File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 176, in <module>
    all_data = json.loads(f.read())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 6 column 3 (char 805)

## 执行结束... 2022-03-04 11:57:11 耗时 3 秒


大佬又出现新问题了/(ㄒoㄒ)/~~

**Comment by KotoriMinami** [comment]
> json.loads(f.read())



> ## 开始执行... 2022-03-04 11:57:08
> Traceback (most recent call last): File "/ql/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 176, in all_data = json.loads(f.read()) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 6 column 3 (char 805)
> 
> ## 执行结束... 2022-03-04 11:57:11 耗时 3 秒
> 大佬又出现新问题了/(ㄒoㄒ)/~~

你对应的配置文件有复制过去吗

**Comment by 659797578** [comment]
> 

复制过去了，ck也按配置文件里的说明添加上了，唯一不一样的就是lxml依赖Python3里装不上，Linux里装上了。requests-html这个也装不上，装的requests，不知道有没有关系。。。安装完依赖第一次运行的时候没添加CK，运行日志显示账号信息错误，添加完ck后就是上面那个日志的情况了，后面尝试把CK全删了，但是也没出现账号信息错误，日志打印的还是上面这段信息。大佬救救我/(ㄒoㄒ)/~~

**Comment by KotoriMinami** [comment]
> > 
> 
> 复制过去了，ck也按配置文件里的说明添加上了，唯一不一样的就是lxml依赖Python3里装不上，Linux里装上了。requests-html这个也装不上，装的requests，不知道有没有关系。。。安装完依赖第一次运行的时候没添加CK，运行日志显示账号信息错误，添加完ck后就是上面那个日志的情况了，后面尝试把CK全删了，但是也没出现账号信息错误，日志打印的还是上面这段信息。大佬救救我/(ㄒoㄒ)/~~

报错看起来是解析json的时候有问题， 你把你的json内容放这里看看格式校验正常不。
https://www.bejson.com/

**Comment by 659797578** [comment]
json验证了是没问题的，不过必须要2个账号，1个账号的话就算验证正确脚本也跑不通，没办法我就放了2个账号，现在的问题是，我刚刚抓的ck，放到json里，一运行就提示我账号过期...

**Comment by KotoriMinami** [comment]
> json验证了是没问题的，不过必须要2个账号，1个账号的话就算验证正确脚本也跑不通，没办法我就放了2个账号，现在的问题是，我刚刚抓的ck，放到json里，一运行就提示我ck过期...

我试了下    只填1个帐号是能正常跑通的  
形式如下：
{
  "MUSIC_COPARTNER": [
    {
      "cookie": "_ntes_nuid=xxx; _ns=xxx; _ntes_nnid=xxx; UM_distinctid=xxx; NMTID=xxx; WNMCID=xxx; WEVNSM=xxx; __csrf=xxx; MUSIC_U=xxx; ntes_kaola_ad=xxx; _iuqxldmzr_=xxx; JSESSIONID-WYYY=xxx;"
    }
  ]
}
然后看代码上好像不管填几个都只会跑第一个，这个我回头修复一下

**Comment by 659797578** [comment]
唉，多谢大佬的帮助，现在还是CK过期，刚抓的ck运行就提时ck过期，不知道是哪的问题，看来是无缘了。多谢大佬这几天的帮助/(ㄒoㄒ)/~~

**Comment by KotoriMinami** [comment]
> 唉，多谢大佬的帮助，现在还是CK过期，刚抓的ck运行就提时ck过期，不知道是哪的问题，看来是无缘了。多谢大佬这几天的帮助/(ㄒoㄒ)/~~

哈.. 不应该啊, 你cookie怎么抓的

**Comment by 659797578** [comment]
就是网页F12啊，我猜是不是之前那lxml和requests-html这俩依赖的原因？lxml在Python3里装不上装到了linux下，requests-html装不上装的requests。其他的跟你教程里面的操作一致😭😭😭

**Comment by KotoriMinami** [comment]
> 就是网页F12啊，我猜是不是之前那lxml和requests-html这俩依赖的原因？lxml在Python3里装不上装到了linux下，requests-html装不上装的requests。其他的跟你教程里面的操作一致😭😭😭

我在想有没有一种可能.. 你不是音乐合伙人..😳😳
