### ISSUE TITLE
配置相关问题

### ISSUE THREAD

**Issue by shenjoyao** [KotoriMinami/qinglong-sign#8]
您
![2022-03-02_232207](https://user-images.githubusercontent.com/58834978/156391619-4b17c35f-70de-4ff7-b3e4-34716bfd4dd4.jpg)
好，谢谢你的分享，但是使用中遇到一些问题。该怎样抓包配置？网页版的cookie为什么不全？

**Comment by KotoriMinami** [comment]
> 您 ![2022-03-02_232207](https://user-images.githubusercontent.com/58834978/156391619-4b17c35f-70de-4ff7-b3e4-34716bfd4dd4.jpg) 好，谢谢你的分享，但是使用中遇到一些问题。该怎样抓包配置？网页版的cookie为什么不全？

抓包参考 #3
cookie不全你可以先放进去试试，只要能正常评分就不影响
